# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSStoryBookDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSStoryBookDemo
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Buttons+Theming'
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/TextFields+Theming'
  pod 'MaterialComponents/ProgressView'
  pod 'MaterialComponents/ActivityIndicator'
  pod 'MaterialComponents/Slider'
  pod 'MaterialComponents/schemes/Color'
end
